(function(a){a.fn.easySlider=function(b){var c={prevId:"prevBtn",prevText:"Previous",nextId:"nextBtn",nextText:"Next",controlsPlace:false,controlsId:"controls",controlsFade:true,firstId:"firstBtn",firstText:"First",firstShow:false,lastId:"lastBtn",lastText:"Last",lastShow:false,vertical:false,speed:800,auto:true,pause:2000,continuous:false,numeric:false};
var b=a.extend(c,b);this.each(function(){var d=a(this);var m=d.find("li");var j=d.find("ul");var y=m.length;var u=m.width();var l=m.height();var n=true;d.width(u);d.height(l);d.css("overflow","hidden");
j.css("width",y*u);var o=y-1;var x=0;if(b.continuous){j.prepend(a("ul li:last-child",d).clone().css("margin-left","-"+u+"px"));j.append(a("ul li:nth-child(2)",d).clone());j.css("width",(y+1)*u);m=d.find("li")
}if(!b.vertical){m.css("float","left")}if(b.controlsPlace!=false){var k=new Array();k[0]='<ol id="'+b.controlsId+'" class="clearfix">';for(var g=1;g<=y;g++){if(b.numeric){k[g]='<li><a href="#" data-id="'+g+'">'+g+"</a></li>"
}else{k[g]='<li><a href="#" data-id="'+g+'">&nbsp;</a></li>'}}k[k.length]="</ol>";var v=a(b.controlsPlace);v.append(k.join("\n"));v.find("a").live("click",function(){e(a(this).data("id")-1,true);return false
})}function f(h){if(b.controlsPlace!=false){h=parseInt(h);v.find("li").removeClass("current");v.find("li:eq("+h+")").addClass("current")}}function r(){if(x>o){x=0}if(x<0){x=o}if(!b.vertical){j.css("margin-left",(x*u*-1))
}else{j.css("margin-left",(x*l*-1))}n=true;f(x)}function e(h,i){if(n){n=false;var s=x;switch(h){case"next":x=(s>=o)?(b.continuous?0:o):x+1;break;case"prev":x=(x<=0)?(b.continuous?x-1:0):x-1;break;case"first":x=0;
break;case"last":x=o;break;default:x=h;break}var w=Math.abs(s-x);var t=w*b.speed;if(!b.vertical){p=(x*u*-1);j.animate({marginLeft:p},{queue:false,duration:t,complete:r})}else{p=(x*l*-1);j.animate({marginTop:p},{queue:false,duration:t,complete:r})
}if(i){clearTimeout(q)}if(b.auto&&h=="next"&&!i){q=setTimeout(function(){e("next",false)},w*b.speed+b.pause)}}}var q;if(b.auto){q=setTimeout(function(){e("next",false)},b.pause)}f(0)})}})(jQuery);(function(c){var a=c.scrollTo=function(d,f,g){c(window).scrollTo(d,f,g)};a.defaults={axis:"xy",duration:parseFloat(c.fn.jquery)>=1.3?0:1};a.window=function(d){return c(window)._scrollable()};c.fn._scrollable=function(){return this.map(function(){var d=this,f=!d.nodeName||c.inArray(d.nodeName.toLowerCase(),["iframe","#document","html","body"])!=-1;
if(!f){return d}var g=(d.contentWindow||d).document||d.ownerDocument||d;return c.browser.safari||g.compatMode=="BackCompat"?g.body:g.documentElement})};c.fn.scrollTo=function(f,e,d){if(typeof e=="object"){d=e;
e=0}if(typeof d=="function"){d={onAfter:d}}if(f=="max"){f=9000000000}d=c.extend({},a.defaults,d);e=e||d.speed||d.duration;d.queue=d.queue&&d.axis.length>1;if(d.queue){e/=2}d.offset=b(d.offset);d.over=b(d.over);
return this._scrollable().each(function(){var n=this,l=c(n),m=f,j,k={},h=l.is("html,body");switch(typeof m){case"number":case"string":if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(m)){m=b(m);break}m=c(m,this);
case"object":if(m.is||m.style){j=(m=c(m)).offset()}}c.each(d.axis.split(""),function(q,r){var t=r=="x"?"Left":"Top",s=t.toLowerCase(),v="scroll"+t,p=n[v],g=a.max(n,r);if(j){k[v]=j[s]+(h?0:p-l.offset()[s]);
if(d.margin){k[v]-=parseInt(m.css("margin"+t))||0;k[v]-=parseInt(m.css("border"+t+"Width"))||0}k[v]+=d.offset[s]||0;if(d.over[s]){k[v]+=m[r=="x"?"width":"height"]()*d.over[s]}}else{var u=m[s];k[v]=u.slice&&u.slice(-1)=="%"?parseFloat(u)/100*g:u
}if(/^\d+$/.test(k[v])){k[v]=k[v]<=0?0:Math.min(k[v],g)}if(!q&&d.queue){if(p!=k[v]){i(d.onAfterFirst)}delete k[v]}});i(d.onAfter);function i(g){l.animate(k,e,d.easing,g&&function(){g.call(this,f,d)})}}).end()
};a.max=function(g,j){var n=j=="x"?"Width":"Height",k="scroll"+n;if(!c(g).is("html,body")){return g[k]-c(g)[n.toLowerCase()]()}var o="client"+n,f=g.ownerDocument.documentElement,d=g.ownerDocument.body;
return Math.max(f[k],d[k])-Math.min(f[o],d[o])};function b(d){return typeof d=="object"?d:{top:d,left:d}}})(jQuery);(function(d){var a=location.href.replace(/#.*/,"");var c=d.localScroll=function(e){d("body").localScroll(e)};c.defaults={duration:1000,axis:"y",event:"click",stop:true,target:window,reset:true};c.hash=function(f){if(location.hash){f=d.extend({},c.defaults,f);
f.hash=false;if(f.reset){var g=f.duration;delete f.duration;d(f.target).scrollTo(0,f);f.duration=g}b(0,location,f)}};d.fn.localScroll=function(e){e=d.extend({},c.defaults,e);return e.lazy?this.bind(e.event,function(g){var h=d([g.target,g.target.parentNode]).filter(f)[0];
if(h){b(g,h,e)}}):this.find("a,area").filter(f).bind(e.event,function(g){b(g,this,e)}).end().end();function f(){return !!this.href&&!!this.hash&&this.href.replace(this.hash,"")==a&&(!e.filter||d(this).is(e.filter))
}};function b(i,p,g){var q=p.hash.slice(1),o=document.getElementById(q)||document.getElementsByName(q)[0];if(!o){return}if(i){i.preventDefault()}var n=d(g.target);if(g.lock&&n.is(":animated")||g.onBefore&&g.onBefore.call(g,i,o,n)===false){return
}if(g.stop){n.stop(true)}if(g.hash){var m=o.id==q?"id":"name",l=d("<a> </a>").attr(m,q).css({position:"absolute",top:d(window).scrollTop(),left:d(window).scrollLeft()});o[m]="";d("body").prepend(l);location=p.hash;
l.remove();o[m]=q}n.scrollTo(o,g).trigger("notify.serialScroll",[o])}})(jQuery);(function(b){var c={autoPlay:true,speed:5000,text:{play:"",stop:"",previous:"Previous",next:"Next"},transition:[1],showCaption:true,IESafe:false,showTooltips:false,carousel:false,carouselVertical:false,animationFinished:null,buildFinished:null,bindFinished:null,startOn:0,thumbOpacity:0.4,hoverPause:false,thumbName:"-thumb"};
b.fn.PikaChoose=function(d){return this.each(function(){b(this).data("pikachoose",new a(this,d))})};b.PikaChoose=function(h,i){this.options=b.extend({},c,i||{});this.list=null;this.image=null;this.anchor=null;
this.caption=null;this.imgNav=null;this.imgPlay=null;this.imgPrev=null;this.imgNext=null;this.textNext=null;this.textPrev=null;this.previous=null;this.next=null;this.aniWrap=null;this.aniDiv=null;this.aniImg=null;
this.thumbs=null;this.transition=null;this.active=null;this.tooltip=null;this.animating=false;this.stillOut=null;this.counter=null;this.timeOut=null;if(typeof(this.options.data)!="undefined"){h=b("<ul></ul>").appendTo(h);
b.each(this.options.data,function(){if(typeof(this.link)!="undefined"){var e=b("<li><a href='"+this.link+"'><img></a></li>").appendTo(h);if(typeof(this.title)!="undefined"){e.find("a").attr("title",this.title)
}}else{var e=b("<li><img></li>").appendTo(h)}if(typeof(this.caption)!="undefined"){e.append("<span>"+this.caption+"</span>")}if(typeof(this.thumbnail)!="undefined"){e.find("img").attr("ref",this.image);
e.find("img").attr("src",this.thumbnail)}else{e.find("img").attr("src",this.image)}})}if(h.nodeName=="UL"||h.nodeName=="OL"||h instanceof jQuery){this.list=b(h);this.build();this.bindEvents()}else{return
}var j=0;var d=0;for(var g=0;g<25;g++){var f='<div col="'+j+'" row="'+d+'"></div>';this.aniDiv.append(f);j++;if(j==5){d++;j=0}}};var a=b.PikaChoose;a.fn=a.prototype={pikachoose:"4.3.1"};b.fn.pikachoose=b.fn.PikaChoose;
a.fn.extend=a.extend=b.extend;a.fn.extend({build:function(){this.step=0;this.wrap=this.list.parent().find(".pika-stage");this.image=b("<img>").appendTo(this.wrap);this.imgNav=b("<div class='pika-imgnav'></div>").insertAfter(this.image);
this.imgPlay=b("<a></a>").appendTo(this.imgNav);this.counter=b("<span class='pika-counter'></span>").appendTo(this.imgNav);if(this.options.autoPlay){this.imgPlay.addClass("pause")}else{this.imgPlay.addClass("play")
}this.imgPrev=b("<a class='previous'></a>").insertAfter(this.imgPlay);this.imgNext=b("<a class='next'></a>").insertAfter(this.imgPrev);this.caption=this.list.parent().find(".pika-caption");if(this.options.tooltip==true){this.tooltip=b("<div class='pika-tooltip'></div>").insertAfter(this.list).hide()
}this.aniWrap=b("<div class='pika-aniwrap'></div>").insertAfter(this.imgNav);this.aniImg=b("<img>").appendTo(this.aniWrap).hide();this.aniDiv=b("<div class='pika-ani'></div>").appendTo(this.aniWrap);this.textNav=b("<div class='pika-textnav'></div>").insertAfter(this.aniWrap);
this.textPrev=b("<a class='previous'>"+this.options.text.previous+"</a>").appendTo(this.textNav);this.textNext=b("<a class='next'>"+this.options.text.next+"</a>").appendTo(this.textNav);this.list.children("li").wrapInner("<div class='clip' />");
this.thumbs=this.list.find("img");this.active=this.thumbs.eq(this.options.startOn);this.finishAnimating({source:this.active.attr("ref")||this.active.attr("src"),caption:this.active.parents("li:first").find("span:first").html(),clickThrough:this.active.parent().attr("href")||"",clickThroughTitle:this.active.parent().attr("title")||""});
var d=this;this.thumbs.each(function(){d.createThumb(b(this),d)});if(typeof(this.options.buildFinished)=="function"){this.options.buildFinished(this)}},createThumb:function(g){var d=g;var e=this;b.data(g[0],"clickThrough",d.parent("a").attr("href")||"");
b.data(g[0],"clickThroughTitle",d.parent("a").attr("title")||"");if(d.parent("a").length>0){d.unwrap()}b.data(g[0],"caption",d.next("span").html()||"");d.next("span").remove();b.data(g[0],"source",d.attr("ref")||d.attr("src"));
b.data(g[0],"order",d.closest("ul").find("li").index(d.parents("li")));var f=b.data(g[0]);b("<img />").bind("load",{data:f},function(){if(typeof(e.options.buildThumbStart)=="function"){e.options.buildThumbStart(e)
}d.hover(function(h){clearTimeout(e.stillOut);b(this).stop(true,true).fadeTo(250,1);if(!e.options.showTooltips){return}e.tooltip.show().stop(true,true).html(f.caption).animate({top:b(this).parent().position().top,left:b(this).parent().position().left,opacity:1},"fast")
},function(h){if(!b(this).hasClass("active")){b(this).stop(true,true).fadeTo(250,e.options.thumbOpacity);e.stillOut=setTimeout(e.hideTooltip,700)}});if(f.order==e.options.startOn){d.fadeTo(250,1);d.addClass("active");
d.parents("li").eq(0).addClass("active")}else{d.fadeTo(250,e.options.thumbOpacity)}if(typeof(e.options.buildThumbFinish)=="function"){e.options.buildThumbFinish(e)}}).attr("src",d.attr("src"))},bindEvents:function(){this.thumbs.bind("click",{self:this},this.imgClick);
this.imgNext.bind("click",{self:this},this.nextClick);this.textNext.bind("click",{self:this},this.nextClick);this.imgPrev.bind("click",{self:this},this.prevClick);this.textPrev.bind("click",{self:this},this.prevClick);
this.imgPlay.bind("click",{self:this},this.playClick);this.wrap.bind("mouseenter",{self:this},function(d){d.data.self.imgNav.stop(true,true).fadeIn("slow");if(d.data.self.options.hoverPause==true){clearTimeout(d.data.self.timeOut)
}});this.wrap.bind("mouseleave",{self:this},function(d){d.data.self.imgNav.stop(true,true).fadeOut("slow");if(d.data.self.options.autoPlay==true&&d.data.self.options.hoverPause){d.data.self.timeOut=setTimeout((function(e){return function(){e.nextClick()
}})(d.data.self),d.data.self.options.speed)}});if(this.options.tooltip==true){this.tooltip.bind("mouseenter",{self:this},function(d){clearTimeout(d.data.self.stillOut)})}if(this.options.tooltip==true){this.tooltip.bind("mouseleave",{self:this},function(d){d.data.self.stillOut=setTimeout(d.data.self.hideTooltip,700)
})}if(typeof(this.options.bindsFinished)=="function"){this.options.bindsFinished(this)}},hideTooltip:function(d){b(".pika-tooltip").animate({opacity:0.01})},imgClick:function(h,d){var f=h.data.self;var g=b.data(this);
if(f.animating){return}f.animating=true;f.active.fadeTo(300,f.options.thumbOpacity).removeClass("active");f.active.parents(".active").eq(0).removeClass("active");f.active=b(this);f.active.addClass("active").fadeTo(200,1);
f.active.parents("li").eq(0).addClass("active");b("<img />").bind("load",{self:f,data:g},function(){f.aniDiv.css({height:f.image.height(),width:f.image.width()}).fadeIn("fast");f.aniDiv.children("div").css({width:"20%",height:"20%","float":"left"});
var e=0;if(f.options.transition[0]==-1){e=Math.floor(Math.random()*7)+1}else{e=f.options.transition[f.step];f.step++;if(f.step>=f.options.transition.length){f.step=0}}if(f.options.IESafe&&b.browser.msie){e=1
}f.doAnimation(e,g)}).attr("src",b.data(this).source)},doAnimation:function(i,g){var e=this;e.image.stop(true,false);var f=e.aniDiv.children("div").eq(0).width();var h=e.aniDiv.children("div").eq(0).height();
var d=new Image();g.source=g.source.replace(this.options.thumbName,"");b(d).attr("src",g.source);if(d.height!=e.image.height()||d.width!=e.image.width()){if(i!=0&&i!=1&&i!=7){i=1}}e.aniDiv.css({height:d.height,width:d.width});
e.aniDiv.children().each(function(){var l=b(this);var j=Math.floor(l.parent().width()/5)*l.attr("col");var k=Math.floor(l.parent().height()/5)*l.attr("row");l.css({background:"url("+g.source+") -"+j+"px -"+k+"px",width:"0px",height:"0px",position:"absolute",top:k+"px",left:j+"px","float":"none"})
});e.aniDiv.hide();e.aniImg.hide();switch(i){case 0:e.image.stop(true,true).fadeOut("slow",function(){e.image.attr("src",g.source).fadeIn("slow",function(){e.finishAnimating(g)})});break;case 1:e.aniDiv.hide();
e.aniImg.height(e.image.height()).hide().attr("src",g.source);b.when(e.image.fadeOut("slow"),e.aniImg.eq(0).fadeIn("slow")).done(function(){e.finishAnimating(g)});break;case 2:e.aniDiv.show().children().hide().each(function(k){var j=k*30;
b(this).css({opacity:0.1}).show().delay(j).animate({opacity:1,width:f,height:h},200,"linear",function(){if(e.aniDiv.find("div").index(this)==24){e.finishAnimating(g)}})});break;case 3:e.aniDiv.show().children("div:lt(5)").hide().each(function(k){var j=b(this).attr("col")*100;
b(this).css({opacity:0.1,width:f}).show().delay(j).animate({opacity:1,height:e.image.height()},700,"linear",function(){if(e.aniDiv.find(" div").index(this)==4){e.finishAnimating(g)}})});break;case 4:e.aniDiv.show().children().hide().each(function(k){if(k>4){return
}var j=b(this).attr("col")*10;h=e.gapper(b(this),h);b(this).css({opacity:0.1,height:"100%"}).show().animate({opacity:1,width:f},500,"linear",function(){if(e.aniDiv.find(" div").index(this)==4){e.finishAnimating(g)
}})});break;case 5:e.aniDiv.show().children().show().each(function(k){var j=k*Math.floor(Math.random()*5)*7;h=e.gapper(b(this),h);if(b(".animation div").index(this)==24){j=600}b(this).css({height:h,width:f,opacity:0.01}).delay(j).animate({opacity:1},600,function(){if(e.aniDiv.find(" div").index(this)==24){e.finishAnimating(g)
}})});break;case 6:e.aniDiv.height(e.image.height()).hide().css({background:"url("+g.source+") top left no-repeat"});e.aniDiv.children("div").hide();e.aniDiv.css({width:0}).show().animate({width:e.image.width()},"slow",function(){e.finishAnimating(g);
e.aniDiv.css({background:"transparent"})});break;case 7:e.wrap.css({overflow:"hidden"});e.aniImg.height(e.image.height()).hide().attr("src",g.source);e.aniDiv.hide();e.image.css({position:"relative"}).animate({left:"-"+e.wrap.outerWidth()+"px"});
e.aniImg.show();e.aniWrap.css({left:e.wrap.outerWidth()}).show().animate({left:"0px"},"slow",function(){e.finishAnimating(g)});break}},finishAnimating:function(f){this.animating=false;f.source=f.source.replace(this.options.thumbName,"");
this.image.attr("src",f.source);this.image.css({left:"0"});this.image.show();var d=this;b("<img />").bind("load",function(){d.aniImg.hide();d.aniDiv.hide()}).attr("src",f.source);var g=this.list.find("img").index(this.active);
g++;var e=this.list.find("img").length;this.counter.html(g+"/"+e);if(f.clickThrough!=""){if(this.anchor==null){this.anchor=this.image.wrap("<a>").parent()}this.anchor.attr("href",f.clickThrough);this.anchor.attr("title",f.clickThroughTitle)
}else{if(this.image.parent("a").length>0){this.image.unwrap()}this.anchor=null}if(this.options.showCaption&&f.caption!=""&&f.caption!=null){this.caption.html(f.caption)}if(this.options.autoPlay==true){var d=this;
clearTimeout(this.timeOut);this.timeOut=setTimeout((function(h){return function(){h.nextClick()}})(this),this.options.speed,this.timeOut)}if(typeof(this.options.animationFinished)=="function"){this.options.animationFinished(this)
}},gapper:function(d,e){if(d.attr("row")==9&&d.attr("col")==0){var f=ani_divs.height()-(e*9);return f}return e},nextClick:function(i){var g="natural";try{var d=i.data.self;if(typeof(i.data.self.options.next)=="function"){i.data.self.options.next(this)
}}catch(h){var d=this;g="auto"}var f=d.active.parents("li:first").next().find("img");if(f.length==0){f=d.list.find("img").eq(0)}f.trigger("click",{how:g})},prevClick:function(g){if(typeof(g.data.self.options.previous)=="function"){g.data.self.options.previous(this)
}var d=g.data.self;var f=d.active.parents("li:first").prev().find("img");if(f.length==0){f=d.list.find("img:last")}f.trigger("click")},playClick:function(f){var d=f.data.self;d.options.autoPlay=!d.options.autoPlay;
d.imgPlay.toggleClass("play").toggleClass("pause");if(d.options.autoPlay){d.nextClick()}}})})(jQuery);function fixedSidebar(c){if($.browser.msie){if(parseInt($.browser.version)==6){return false}}var b=false;var f=$(c).removeClass("fixed");var e=f.parent();var d=f.offset().top-parseInt(f.css("margin-top"),10);
var a=f.outerHeight();$(window).unbind("scroll").bind("scroll",function(){var g=(e.offset().top+e.height())-(a+10);var i=window.pageYOffset;if(i==undefined){i=document.documentElement.scrollTop}var h=window.innerHeight/2;
if(isNaN(h)){h=document.documentElement.clientHeight/2}$("#container .anchor-item").each(function(j){var k=$(this).offset().top-i;if(k<=h){f.find("li").removeClass("selected");f.find("li:eq("+j+")").addClass("selected")
}});if(i>=g){f.removeClass("fixed").addClass("static");b=false;return}if(!b&&i>=d){f.removeClass("static").addClass("fixed");b=true}if(b&&i<=d){f.removeClass("static").removeClass("fixed");b=false}});$(window).scroll()
}function slideSwitch(d){var c=$(d);var a=c.find(".active");if(a.length===0){a=c.children(":last")}var b=a.next().length?a.next():c.children(":first");a.addClass("last-active");b.css({opacity:0}).addClass("active").animate({opacity:1},1000,function(){a.removeClass("active last-active")
})}$(document).ready(function(){setInterval("slideSwitch('#header .tagline')",6000);setInterval("slideSwitch('#clients-slide')",5000);switch($("body").data("page")){case"home":$("#slider").easySlider({controlsPlace:"#banner footer",controlsFade:true,auto:true,continuous:true,numeric:false});
break;case"company":fixedSidebar("#scroll");$("#scroll").localScroll();break;case"site":fixedSidebar("#scroll");break;case"gallery":fixedSidebar("#scroll");$("#gallery").PikaChoose({thumbOpacity:0.4,hoverPause:true,transition:[4]});
break}if($.browser.msie){if(parseInt($.browser.version)==6){$("#header nav li:first").addClass("first-child");$("#container aside").css("height",$("#container .main-content").height())}}$("body").addClass("js-finished")
});